version: "3.8"

services:
  mysql:
    build: ./mysql
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d
    image: nene_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_DATABASE=ctaglearn
    ports:
      - 3306:3306
    restart: always
